name: TQC
module: sb3_contrib
kwargs:
  batch_size: 512
  buffer_size: 1_000_000
  gamma: 0.98
  learning_rate: 0.005
  learning_rate_schedule: linear
  policy: MultiInputPolicy
  policy_kwargs: 
    net_arch: 
      - 512
      - 512
      - 512
    n_critics: 2
  tau: 0.005
  learning_starts: 1000
