# @package _global_
detector:
  _target_: anomrl.algos.detectors.ProbEnsDMDetector
  model_kwargs: 
    lr: 0.0005

data_module:
  _target_: anomrl.data.datamodules.VectorObsDataModule
  batch_size: 1

model_tag: PEDM

trainer:
  max_epochs: 250
  check_val_every_n_epoch: 10
  early_stopping: false
  progress_bar: true
  save_best_checkpoint: false

